apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://external-secrets.github.io/kubernetes-external-secrets/'  # chart repo
    chart: kubernetes-external-secrets
    targetRevision: "latest"
    helm:
      values: |
        # use existing SA (we created & annotated it)
        serviceAccount:
          create: false
          name: external-secrets-sa
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
